/**
 * Data governance registry — single source of truth for every shared data
 * artifact in the virtualpc ecosystem (game JSON, asset registries, wiki
 * terms, DB schemas).
 *
 * Each entry tracks: who owns it (agent name), where it lives (path/URL),
 * what schema it claims to follow, when it was last updated, what license
 * applies, and a free-text lineage note (what produced it / what consumes
 * it).
 *
 * Owned by the Governor agent. Read by the wiki, asset pipeline, and any
 * agent that wants to know "where does this term come from?".
 *
 * Persisted to data/governance.json with the same dirty-flag + 5s save
 * pattern as the task engine.
 */
import * as fs from 'fs';
import * as path from 'path';
import logger from '../../utils/logger';
import { sharedDataPath, ASSET_REGISTRY_PATH, PROJECT_ROOT } from '../../config/paths';

export type GovernanceKind =
  | 'shared-data'      // shared/*.json on the webgame
  | 'asset-registry'   // asset registries (EDS2, repo-local)
  | 'wiki-term'        // a single wiki entry — ties to wiki.json
  | 'schema'           // DB / Kafka schema
  | 'config'           // shared configuration
  | 'license';         // license / attribution record

export interface GovernanceEntry {
  /** Stable id — kebab-case, e.g. "shared-elements-json" */
  id: string;
  /** Human-readable name */
  name: string;
  kind: GovernanceKind;
  /** Owning agent (must be in AGENT_META) */
  owner: string;
  /** Filesystem path or URL — relative to project root for local files */
  source: string;
  /** Optional schema reference (file path or JSON Schema URL) */
  schema?: string;
  /** Free-text lineage: where this came from + who consumes it */
  lineage?: string;
  /** Last-updated ISO timestamp */
  updatedAt: string;
  /** License or attribution string */
  license?: string;
  /** Tags for cross-referencing (e.g. ['chemistry', 'quantum', 'wiki']) */
  tags?: string[];
}

interface GovernanceState {
  entries: GovernanceEntry[];
}

const GOVERNANCE_PATH = path.join(__dirname, '..', '..', '..', 'data', 'governance.json');
let state: GovernanceState = { entries: [] };
let dirty = false;

function ensureLoaded() {
  if (state.entries.length > 0) return;
  if (!fs.existsSync(GOVERNANCE_PATH)) {
    state = { entries: defaultEntries() };
    dirty = true;
    save();
    return;
  }
  try {
    const raw = fs.readFileSync(GOVERNANCE_PATH, 'utf8');
    state = JSON.parse(raw);
    if (!state.entries) state.entries = [];
  } catch (e: any) {
    logger.warn(`governance: failed to load ${GOVERNANCE_PATH}: ${e.message}`);
    state = { entries: defaultEntries() };
    dirty = true;
  }
}

function defaultEntries(): GovernanceEntry[] {
  // Seed with the artifacts we know exist so the registry isn't empty
  // on first boot. Governor will add more as they're discovered.
  const now = new Date().toISOString();
  return [
    {
      id: 'shared-elements-json',
      name: 'Periodic-table elements catalogue',
      kind: 'shared-data',
      owner: 'Governor',
      source: sharedDataPath('elements.json'),
      lineage: 'Authored by Atlas + Vice from IUPAC 2024 atomic-weight table. Consumed by /api/elements and the periodic-table page.',
      updatedAt: now,
      license: 'CC-BY-4.0 (IUPAC reference data)',
      tags: ['chemistry', 'periodic-table'],
    },
    {
      id: 'shared-reactions-json',
      name: 'Chemical reactions catalogue',
      kind: 'shared-data',
      owner: 'Governor',
      source: sharedDataPath('reactions.json'),
      lineage: 'Curated by Atlas. Reaction conditions cross-referenced in reactions-conditions.json. Consumed by chemistry bench + quest engine.',
      updatedAt: now,
      license: 'CC-BY-4.0',
      tags: ['chemistry', 'reactions'],
    },
    {
      id: 'shared-quests-json',
      name: 'Quest catalogue',
      kind: 'shared-data',
      owner: 'Governor',
      source: sharedDataPath('quests.json'),
      lineage: 'Authored by Vice. Quest unlocks tied to age-bands.json + achievements.json.',
      updatedAt: now,
      license: 'proprietary (molgang)',
      tags: ['game', 'quests'],
    },
    {
      id: 'asset-registry-eds2',
      name: 'EDS2 canonical asset registry',
      kind: 'asset-registry',
      owner: 'Atlas',
      source: ASSET_REGISTRY_PATH,
      lineage: `Generated by scripts/build-asset-registry.js scanning ${PROJECT_ROOT}/molgang-assets/. Consumed by webgame asset loader + Three.js viewer.`,
      updatedAt: now,
      license: 'mixed (per-asset; see asset.license.txt siblings)',
      tags: ['assets', '3d'],
    },
    {
      id: 'wiki-terms-json',
      name: 'Webgame wiki — game + quantum-chemistry terms',
      kind: 'wiki-term',
      owner: 'Governor',
      source: sharedDataPath('wiki-terms.json'),
      lineage: 'Authored by Kimi (taskType:docs) from project glossaries + IUPAC quantum-chem terminology. Pixel renders the /wiki page.',
      updatedAt: now,
      license: 'CC-BY-4.0',
      tags: ['wiki', 'quantum-chemistry', 'documentation'],
    },
  ];
}

let saveTimer: NodeJS.Timeout | null = null;
function scheduleSave() {
  if (saveTimer) return;
  saveTimer = setTimeout(() => {
    saveTimer = null;
    save();
  }, 5000);
}

function save() {
  if (!dirty) return;
  try {
    fs.mkdirSync(path.dirname(GOVERNANCE_PATH), { recursive: true });
    fs.writeFileSync(GOVERNANCE_PATH, JSON.stringify(state, null, 2));
    dirty = false;
  } catch (e: any) {
    logger.warn(`governance: save failed: ${e.message}`);
  }
}

export function listEntries(filter?: { kind?: GovernanceKind; owner?: string; tag?: string }): GovernanceEntry[] {
  ensureLoaded();
  let out = [...state.entries];
  if (filter?.kind) out = out.filter(e => e.kind === filter.kind);
  if (filter?.owner) out = out.filter(e => e.owner === filter.owner);
  if (filter?.tag) out = out.filter(e => (e.tags || []).includes(filter.tag!));
  return out.sort((a, b) => a.id.localeCompare(b.id));
}

export function getEntry(id: string): GovernanceEntry | undefined {
  ensureLoaded();
  return state.entries.find(e => e.id === id);
}

export function registerEntry(entry: Omit<GovernanceEntry, 'updatedAt'> & { updatedAt?: string }): GovernanceEntry {
  ensureLoaded();
  const now = new Date().toISOString();
  const next: GovernanceEntry = { ...entry, updatedAt: entry.updatedAt || now };
  const idx = state.entries.findIndex(e => e.id === entry.id);
  if (idx >= 0) state.entries[idx] = next;
  else state.entries.push(next);
  dirty = true;
  scheduleSave();
  return next;
}

export function getLineage(termOrId: string): { entry?: GovernanceEntry; relatedByTag: GovernanceEntry[] } {
  ensureLoaded();
  const entry = state.entries.find(e => e.id === termOrId || e.name.toLowerCase() === termOrId.toLowerCase());
  if (!entry) return { relatedByTag: [] };
  const tags = new Set(entry.tags || []);
  const related = state.entries.filter(e => e.id !== entry.id && (e.tags || []).some(t => tags.has(t)));
  return { entry, relatedByTag: related };
}

export function flushSync() {
  if (dirty) save();
}
